export enum Instrument {
  Violin = 0,
  Viola = 1,
  Cello = 2,
  DoubleBass = 3,
  Flute = 4,
  Oboe = 5,
  Clarinet = 6,
  Bassoon = 7,
  FrenchHorn = 8,
  Trumpet = 9,
  Trombone = 10,
  Tuba = 11,
  Percussion = 12,
  Harp = 13,
  Piano = 14,
  Saxophone = 15,
}
